In [10]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [11]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = self.initia(shape = (input_dim, units))
        self.w = tf.Variable(
            initial_value=w_init,
            trainable=True
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(units,), dtype="float32"), trainable=True
        )
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    def initia(self, shape):
        return tf.cast(tf.sign(2 * np.random.randint(0,2, shape) - 1), dtype="float32")

In [12]:
units = 128
input_size = 10
x = tf.one_hot([0,1,2,3,4,5,6,7,8,9], input_size)
print(x)
linear_layer = Linear(units, input_size)
print(linear_layer.w)
y = linear_layer(x)
print(y)

tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]], shape=(10, 10), dtype=float32)
<tf.Variable 'Variable:0' shape=(10, 128) dtype=float32, numpy=
array([[-1.,  1.,  1., ..., -1.,  1., -1.],
       [ 1.,  1., -1., ...,  1., -1., -1.],
       [-1.,  1.,  1., ..., -1.,  1., -1.],
       ...,
       [ 1., -1.,  1., ..., -1.,  1.,  1.],
       [-1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1.,  1.]], dtype=float32)>
tf.Tensor(
[[-1.  1.  1. ... -1.  1. -1.]
 [ 1.  1. -1. ...  1. -1. -1.]
 [-1.  1.  1. ... -1.  1. -1.]
 ...
 [ 1. -1.  1. ... -1.  1.  1.]
 [-1. -1.  1. ...  1.  1. -1.]
 [ 1. -1.  1. ...  1.  1.  1.]], shape=(10, 128), dtype=float32)
